version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:       
      - export tag=$(docker images --format "{{.Repository}}:{{.Tag}}" |grep myapplication)
      - echo | docker images
      - echo $tag
      - docker push $tag.
